<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>System.Diagnostics.EnhancedStackTrace</RootNamespace>
		<AssemblyName>System.Diagnostics.EnhancedStackTrace</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="System.Diagnostics.EnhancedStackTrace.Tests" />
	</ItemGroup>
</Project>
